### ISSUE TITLE
ترجمه فصل چهار

### ISSUE THREAD

**Issue by hjavadish** [progit2-fa/progit2#11]
<div dir="rtl">

فصل چهار کتاب گیت هنوز ترجمه نشده. میتونه گزینه ی خوبی برای هکتوبرفست باشه.
</div>

**Comment by MSafariyan** [comment]
بنده فصل چهار رو ترجمه میکنم

**Comment by Davoodeh** [comment]
@mahdisafarian 
تا پیش از آپدیت پروژه به صورتی که تا اینجا کار کردیم روی فورک من پوش کنید
با تشکر.

**Comment by hjavadish** [comment]
<div dir="rtl">

پروژه بروز شد.

**Comment by hjavadish** [comment]
پیش نویسی از فصل چهارم ترجمه و بارگزاری شده است، پس این بحث به پایان می رسد.

**Comment by Davoodeh** [comment]
@mahdisafarian 
من درخواست پول فصل چهار رو باز می‌کنم و مشکلات موجود رو حین بازبینی رفع می‌کنیم و در برنچی دیگه ارائه می‌کنیم.
