### ISSUE TITLE
Theme is not attractive & out-date repo 

### ISSUE THREAD

**Issue by MSafariyan** [progit2-fa/progit2#16]
تم موجود که در نسخه فارسی استفاده می‌شود جذابیتی ندارد و کمی بد ریخت نمایش داده می‌شود.
ظاهرا فورک موجود نسبت به نسخه اصلی کتاب انگلیسی قدیمی تر است و همچنین استاندارد واحدی برای نحوه نگارش وجود ندارد که این خودش یک مشکل اساسی است. #15 
لطفا رسیدگی کنید.

--با تشکر

**Comment by hjavadish** [comment]
<div dir="rtl">

با تشکر از شما بروز رسانی جدید تایید شد.
