### ISSUE TITLE
We can help!

### ISSUE THREAD

**Issue by Davoodeh** [progit2-fa/progit2#20]
سلام، 
حین اینکه فایل
TRANSLATING.md
ریپوی اصلی رو می‌خوندم دیدم که مسلتزم این هستم که بیام اینجا و یه ایشو باز کنم و خودم رو معرفی کنم قبل از شروع کار.

الآن که در عمل انجام شده قرار گرفتم و کار شروع شده و بنا به دلایل شخصی باید هرچه سریع‌تر (با هماهنگی پاسخ یا بی‌پاسخ از سمت این مخزن) کار رو به پایان برسونیم.

اما گفتم این رو باز کنم و بگم که کارای زیر داره اتفاق میوفته:
بازنویسی نوشته‌های قبلی به علت مشکلات *بی‌شمار*
آپدیت ریپو به نسخه امروز از چهار سال قبل
ترجمه فصل‌های جدید

**Comment by hjavadish** [comment]
<div dir="rtl">

سلام دوست عزیز.   
از این که تو ترجمه ی این کتاب دارید کمک می کنید تشکر می کنم.
برای ترجمه ی کتاب بهتره ابتدا یه راهنما نوشته بشه تا بتونیم چند نفر همزمان روی یک کتاب ترجمه داشته باشند.   
هم هماهنگی بین ترجمه واژه ها و اصلاحات زبانی بیشتر بشه.
مثلا در ترجمه system **سامانه** باید بگیم و یا **سیستم** 
و یا مثلا همزه در زبان فارسی داریم که بزاریم یا باید به جاش از ی تنها استفاده بشه.
در عباراتی مانند "**جمله ی قبلی**"
 و هم اینکه این راهنما از دوباره کاری در امر ترجمه جلو گیری کنه.

به هر شکل پیشنهاد می کنم دست کم در همین بخش issues این گونه بحث ها را می توان باز کرد.
در ضمن یه پیشنهاد هم دارم که باید در همون راهنما هم آورده بشهو به نظرم میاد بهتره که ترجمه ها رو پاراگراف به پاراگراف ارسال کنیم (commit و ثبت PR) تا تایید نشدن یه پاراگراف و درخواست بازبینی اون منجر به معطل موندن حجم زیادی از کارای دیگه نشه.

**Comment by Davoodeh** [comment]
صحیح
ما به عنوان یه تیم دو نفره خیلی سریع الآن داریم کارو پیش می‌بریم
@mahdisafarian

یک قرارداد کلی هم تنظیم کردیم که در 
TRANSLATION_NOTES
قابل مشاهده است.

در آخر بگم که به نظرم به جای کامیت پاراگراف به پاراگراف ما بنای کار رو بر این گذاشتیم که هر چند ناقص اول یک دور کامل روی کتاب بزنیم بعد در مرحله ویرایستاری ترجمه‌ها رو یکپارچه کنیم و کلمات جا مونده، استاندارد نشده یا موارد مبهم رو اصلاح کنیم. در نتیجه تولید متن مهم‌تر از ویرایشش باشه در این وهله که دست‌وپا گیر نباشه کار کردن.

در مقیاس کوچیک فصل ۱ رو به این نحو ترجمه کردیم و به نظر من الآن کاملا خوانا است.

ضمن اینکه من فورک خودم رو بروزسانی کردم و الآن با فورکی که اینجا هست یکسان نیست.

همچنین بی‌اجازه از شما یه تقسیم کار کوچکی هم انجام دادیم و دوستمون
@mahdisafarian
روی فصل ۲ کار می‌کنه و من ۳ (یک هم که تموم شده)



پول رک فایل یادداشت‌های ترجمه‌ام رو فرستادم لطفاً بررسی شود. #21

**Comment by Davoodeh** [comment]
از اونجایی که مخزن فعالی نیست بحمدالله دستمون برای تعیین استاندارد و بحث خیلی باز هست و سه نفری آروم می‌تونیم پی ببریم کار رو :)

**Comment by Davoodeh** [comment]
اگر سرعت پاسخگویی به این نحو کم هست. جسارتاً می‌خواستم تقاضای دسترسی نوشتن به مخزن رو پیدا کنم تا پروژه رو پیش ببرم.
تا اینجای کار سه فصل اول تموم شدن و یه نقشهٔ راه کلی توی فورک بنده شکل گرفته و دونفری روش کار می‌کنیم...

پیشاپیش از صبر و پاسخگوییتون ممنونم

**Comment by hjavadish** [comment]
> اگر سرعت پاسخگویی به این نحو کم هست. جسارتاً می‌خواستم تقاضای دسترسی نوشتن به مخزن رو پیدا کنم تا پروژه رو پیش ببرم.
> تا اینجای کار سه فصل اول تموم شدن و یه نقشهٔ راه کلی توی فورک بنده شکل گرفته و دونفری روش کار می‌کنیم...
> 
> پیشاپیش از صبر و پاسخگوییتون ممنونم

<div dir="rtl">

فصل سه رو من اینجا #5  گفته بودم که خودم دارم ترجمه می کنم و اگر issue ها رو خونده بودید دچار دوباره کاری نمی شدیم. ولی خب مشکلی نیست .  ارسال کنید حتما تایید می کنم. 

از اونجا که می گید قرار گذاشتید که تولید متن مهم تر از ویراستاری باشه نظرات و بررسی هام رو می زارم برای بعد. 
با تشکر

**Comment by hjavadish** [comment]
> پول رک فایل یادداشت‌های ترجمه‌ام رو فرستادم لطفاً بررسی شود. #21
<div dir="rtl">


این رو هم تایید کردم. ولی توی فارسی همزه نداریم و به نظر می رسه بهتر هست که ی باشه.

**Comment by MSafariyan** [comment]
> > پول رک فایل یادداشت‌های ترجمه‌ام رو فرستادم لطفاً بررسی شود. #21
> 
> این رو هم تایید کردم. ولی توی فارسی همزه نداریم و به نظر می رسه بهتر هست که ی باشه.

من هم گفتم برای راحت‌تر خونده شدن متن از ی استفاده کنیم جای همزه
هم به نگار فارسی نزدیک تره هم بهتر خونده میشه. ولی چون فرهنگستان زبان فارسی و اکثر نویسنده‌ها به صورت  توافقی بر روی همزه توافق کرده بودند تا اینجا گفتن با همزه بنویسیم .

**Comment by Davoodeh** [comment]
با تشکر از پیگیری

بله همونطور که دوستمون @mahdisafarian 
ذکر کرد این موضوع قابل بحث هست اما با توجه به کاربرد گستردش توی اکثر اسناد اینترنتی (مثل ویکی‌پدیا)
به نظر می‌رسه که همزه جاگزین بهتریه.

پیشنهاد می‌کنم برای مرحلهٔ بازبینی (بعد از اینکه یک دور کامل) ترجمه انجام شد روی این موضوع بحث کنیم و یک ایشوی ثانوی ایجاد کنیم که این موضوع در اونجا بحث شه.

**Comment by Davoodeh** [comment]
الآن فصل تا فصل سوم تموم شده
ایشوهای گذشته #5 مال سالهای قبل بودن و ازونجایی که مخزن کلا خوابیده بود تا کمی پیش فکر نمی‌کردم واقعا کاری در حال انجام شدن بود
معذرت‌خواهی می‌کنم از این بابت

اگر موافق باشید من پول رک خودم رو ارائه می‌کنم که اگر شخص دیگه‌ای تصمیم به کار کردن روی پروژه رو داشت از همینجا برداره دیگه.
بعدا بازبینی و مدیریت محتوا رو با هم جلو میبریم اگر عمری باشه

**Comment by Davoodeh** [comment]
#23 پس از این می‌تونیم به روند کاری پروژه برگردیم و به ازای هر فصل یک ایشو باز کنیم و تحت نظر شما کار رو تموم کنیم.

**Comment by Davoodeh** [comment]
با توجه به بروز شدن پروژه و هماهنگ شدنمون فکر می‌کنم دیگه نیازی به این ایشو نباشه
