### ISSUE TITLE
ترجمه فصل ششم

### ISSUE THREAD

**Issue by Davoodeh** [progit2-fa/progit2#26]
فصل شش ترجمه نشده
من ترجمه می‌کنم.

آپدیت برای بسته شدن: با توجه به تأخیر و عدم امکان ترجمه بسته شده.
لطفاً اگر قصد ترجمه فصل ششم رو دارید یه ایشو جدید یا همین رو دوباره باز کنید.

**Comment by hjavadish** [comment]
با تشکر و سپاس
