### ISSUE TITLE
ترجمه فصل اول

### ISSUE THREAD

**Issue by hjavadish** [progit2-fa/progit2#4]
ترجمه فصل اول . سرآغاز

**Comment by angellandros** [comment]
من می‌تونم تویِ ترجمه و ویرایش کمک کنم.

**Comment by hjavadish** [comment]
خب بسم الله.
از کدوم بخش شروع می کنید؟

**Comment by angellandros** [comment]
اولین بخشی که ترجمه نشده:
git basic.

**Comment by Davoodeh** [comment]
به نظرم فصل اول تا بازبینی نهایی که قرار شد بعد از ترجمهٔ اولیهٔ همهٔ فصل‌ها باشه تمام شده فرض میشه در نتیجه دلیلی برای وجود این ایشو وجود نداره.
:)
