### ISSUE TITLE
نحوه‌ی مدیریت پروژه و مرحله‌ی کنونی

### ISSUE THREAD

**Issue by mahdavipanah** [progit2-fa/progit2#6]
<div dir="rtl">
سلام،     

نحوه‌ی مدیریت و اضافه شدن اعضا به organization چطوریه؟ یعنی الان اگه مایل به همکاری باشیم باید چجوری کار رو ادامه بدیم؟
و مرحله‌ی کنونی پروژه چی هست؟ این رو به این دلیل میپرسم چون در issues اینطور به نظر میومد که فصل سوم هم شروع شده ولی وقتی فصل‌ها رو بررسی کردم حتی فصل دو هم ترجمه نشده بود.
</div>

**Comment by hjavadish** [comment]
<div dir="rtl">
سلام
بله . به درستی فرمودید که # بخش سه  # که درباره شاخه هاست در دست ترجمه است و رو به پایان. به زودی همه ی  بخش سه را بنده یکجا انتشار می دهد. 
هر کدام از بخش های دیگر را - جدای از یک و سه - که خواهانید  بسم الله

</div>

**Comment by mahdavipanah** [comment]
<div dir="rtl">
یعنی نحوه‌ی کار به این صورته که من در یک فورک جداگانه برای خودم ترجمه کنم و بعد پول رکوئست بزنم یا امکان اضافه شدنم به  organization و انجام کار در یک شاخه‌ی منحصر بفرد ولی در همین مخزن هم هست؟
</div>

**Comment by hjavadish** [comment]
<div dir="rtl">
سلام دوست گرامی.
با یک فورک جدا کار را آغاز کنید.  پیش از ترجمه بخش گزینش شده را اعلام کنید تا تداخل در ادغام کمتر بوجود آید.
تشکر و سپاس
</div>
